TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += SKSD4.db
# DB += KURAMA.db
DB += S2SD1.db
DB += TR700W.db
DB += TR72NW_socket.db
DB += TR72NW.template
DB += TR72NW.substitutions
DB += K18Magnet.template
DB += K18Magnet.substitutions
DB += ALine.template
DB += ALine.substitutions
DB += BLine.template
DB += BLine.substitutions
DB += Sepa.template
DB += Sepa.substitutions
DB += Accel.template
DB += Accel.substitutions
DB += HDuser.template
DB += HDuser.substitutions
DB += CAENHV_A.template
DB += CAENHV_B.template
DB += CAENHV1-0.substitutions
DB += CAENHV1-2.substitutions
DB += CAENHV1-3.substitutions
DB += CAENHV1-5.substitutions
DB += CAENHV2-0.substitutions
DB += CAENHV2-1.substitutions
DB += CAENHV2-2.substitutions
DB += CAENHV2-6.substitutions
DB += CAENHV2-13.substitutions
DB += CAENHV3-0.substitutions
DB += CAENHV3-2.substitutions
DB += CAENHV3-3.substitutions
DB += CAENHV3-4.substitutions
DB += CAENHV3-6.substitutions
DB += CAENHV3-8.substitutions
DB += CAENHV3-9.substitutions
DB += CAENHV3-11.substitutions
DB += CAENHV3-12.substitutions
DB += CAENHV3-13.substitutions
DB += CAENHV4-0.substitutions
DB += CAENHV4-4.substitutions
DB += CAENHV5-0.substitutions
DB += CAENHV5-3.substitutions
DB += CAENV895.template
DB += CAENV895-vme05.substitutions
DB += CAENV895-vme08.substitutions
DB += CAENV895-ctrl2.substitutions
DB += ZRRX40.template
DB += ZRRX40.substitutions
DB += ZRRX45.template
DB += ZRRX45.substitutions
# DB += GL840_BGO.db
DB += GL840_BGO.template
DB += GL840_BGO.substitutions
DB += GL840_AFT.db
DB += GL840_AFT.template
DB += GL840_AFT.substitutions
DB += HDDAQ.template
DB += HDDAQ.substitutions
DB += HUL_Trigger.template
DB += HUL_Trigger.substitutions
DB += MppcBias.db
# DB += MppcBias.template
# DB += MppcBias.substitutions
DB += GAS.db
DB += Misc.db
DB += MQV9500.template
DB += MQV9500.substitutions
DB += GL840_TPC.template
DB += GL840_TPC.substitutions
DB += GL840_KURAMA.template
DB += GL840_KURAMA.substitutions
DB += SHS.db
DB += HulScaler.db
DB += GL840_DCVth.template
DB += GL840_DCVth.substitutions
DB += PMX18.db
DB += PresSDC.db
# DB += HulScaler.template
# DB += HulScaler.substitutions

#DB += HBJ_LABVIEW.template
#DB += HBJ.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
