TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += SKSD4.db
DB += TR700W.db
DB += K18Magnet.template
DB += K18Magnet.substitutions
DB += ALine.template
DB += ALine.substitutions
DB += Sepa.template
DB += Sepa.substitutions
DB += Accel.template
DB += Accel.substitutions
DB += ZRRX40.template
DB += PWO.substitutions
DB += HBJ_LABVIEW.template
DB += HBJ.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

