TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += SKSD4.db
DB += TR700W.db
DB += K18Magnet.template
DB += K18Magnet.substitutions
DB += ALine.template
DB += ALine.substitutions
DB += Sepa.template
DB += Sepa.substitutions
DB += Accel.template
DB += Accel.substitutions
DB += HDuser.template
DB += HDuser.substitutions
DB += CAENHV_A.template
DB += CAENHV_B.template
DB += CAENHV1-0.substitutions
DB += CAENHV1-2.substitutions
DB += CAENHV1-3.substitutions
DB += CAENHV1-5.substitutions
DB += CAENHV2-0.substitutions
DB += CAENHV2-1.substitutions
DB += CAENHV2-2.substitutions
DB += CAENHV2-6.substitutions
DB += CAENHV2-13.substitutions
DB += CAENHV3-0.substitutions
DB += CAENHV3-2.substitutions
DB += CAENHV3-3.substitutions
DB += CAENHV3-4.substitutions
DB += CAENHV3-6.substitutions
DB += CAENHV3-8.substitutions
DB += CAENHV3-9.substitutions
DB += CAENHV3-11.substitutions
DB += CAENHV3-12.substitutions
DB += CAENHV4-2.substitutions
DB += ZRRX40.template
DB += ZRRX40.substitutions
DB += ZRRX45.template
DB += ZRRX45.substitutions
DB += GL840_BGO.db
# DB += GL840_BGO.template
# DB += GL840_BGO.substitutions
DB += HDDAQ_runno.template
DB += HDDAQ_runno.substitutions

#DB += HBJ_LABVIEW.template
#DB += HBJ.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

